"""
ARC Platform - AI Orchestration Entry Point
A modular, domain-agnostic AI system for processing diverse tasks.
"""

from utils.ai_client import ask_ai, is_model_ready
from utils.conversation_manager import ConversationManager
from utils.formatter import format_user_input
import sys

# ============================================================================
# WELCOME SCREEN
# ============================================================================

def print_welcome():
    """Show welcome message."""
    print("\n" + "="*60)
    print("🤖  ARC Platform - AI Orchestration System")
    print("="*60)
    print("\nWelcome! This is a flexible AI system ready to assist.")
    print("\nCapabilities:")
    print("  💬 Natural language processing")
    print("  🧠 Reasoning and analysis")
    print("  💻 Code generation and review")
    print("  ✨ Creative content generation")
    print("\nCommands: /help /reset /quit")
    print("="*60 + "\n")

def print_help():
    """Show help information."""
    print("\n" + "─"*60)
    print("📖 HELP - System Usage")
    print("─"*60)
    print("\n🤖 SYSTEM CAPABILITIES:")
    print("  • Process natural language queries")
    print("  • Generate responses based on context")
    print("  • Maintain conversation history")
    print("  • Support various task types")
    print("\n💬 EXAMPLE QUERIES:")
    print("  • 'Explain quantum computing'")
    print("  • 'Write a Python function for sorting'")
    print("  • 'Summarize this text'")
    print("  • 'Generate creative content'")
    print("\n⚠️  NOTE: This is an AI system with general capabilities.")
    print("   Responses are generated by AI models and should be verified.")
    print("\n⌨️  COMMANDS:")
    print("  /help  - Show this help")
    print("  /reset - Clear conversation history")
    print("  /quit  - Exit the application")
    print("─"*60 + "\n")

# ============================================================================
# MAIN APPLICATION
# ============================================================================

def main():
    """Main application loop."""
    
    # Show welcome
    print_welcome()
    
    # Check model readiness
    if not is_model_ready():
        print("❌ Model initialization failed. Please restart.\n")
        sys.exit(1)
    
    # Initialize conversation manager
    convo = ConversationManager()
    print("System ready. Enter your query:\n")
    
    while True:
        try:
            # Get user input
            user_input = input("User: ").strip()
            
            # Skip empty input
            if not user_input:
                continue
            
            # Handle exit commands
            if user_input.lower() in ['/quit', 'quit', 'exit']:
                print("\nShutting down. Thank you for using ARC Platform.\n")
                break
            
            # Handle help command
            if user_input.lower() == '/help':
                print_help()
                continue
            
            # Handle reset command
            if user_input.lower() == '/reset':
                convo.reset()
                print("🔄 Conversation history cleared.\n")
                continue
            
            # Format input for processing
            formatted = format_user_input(user_input)
            
            # Process query with AI
            print("⚙️  Processing...", end='', flush=True)
            
            try:
                response = ask_ai(formatted, convo.get_history())
            except Exception as e:
                print(f"\r❌ Error: {e}")
                print("Request failed. Please try again.\n")
                continue
            
            # Clear processing indicator
            print("\r" + " "*20 + "\r", end='')
            
            # Update conversation history
            convo.add_message("user", formatted)
            convo.add_message("assistant", response)
            
            # Display response
            print(f"AI: {response}\n")
        
        except KeyboardInterrupt:
            print("\n\nApplication terminated by user.\n")
            break
        
        except Exception as e:
            print(f"\n❌ Error: {e}\n")
            continue

# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\n❌ Fatal error: {e}")
        print("Application will now exit.\n")
        sys.exit(1)
